# Generated by Django 5.2.1 on 2025-08-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_test_value',
            field=models.BooleanField(default=False),
        ),
    ]
