# Generated by Django 5.2.1 on 2025-08-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_test_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_test_value',
        ),
    ]
