# Generated by Django 5.2.1 on 2025-06-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
