# Generated by Django 5.2.1 on 2025-06-22 10:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_wishlist_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='added_product',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'added_product')},
        ),
    ]
