# Generated by Django 5.2.1 on 2025-06-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_category_slug_alter_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new_arrival',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_trending',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
