# Generated by Django 5.2.1 on 2025-08-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_address_line2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
