# Generated by Django 5.2.1 on 2025-05-17 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreorderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='preorder_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreorderRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preorder_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preorder.preorderrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreorderRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Availabe', 'Available'), ('Not Available', 'Not Available'), ('Awaiting Payment', 'Awaiting Payment'), ('In Progress', 'In Progress'), ('Awaiting Shipment', 'Awaiting Shipment'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('On Hold', 'On Hold')], default='Pending', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preorder_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preorder.preorderrequest')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
