# Generated by Django 5.2.1 on 2025-05-17 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorderrequestcomment',
            name='preorder_request',
        ),
        migrations.AddField(
            model_name='preorderrequest',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='preorderrequest',
            name='order_type',
            field=models.CharField(choices=[('self ', 'For Yourself'), ('gift', 'For a Gift'), ('gift', 'Customized Gift')], default='self', max_length=50),
        ),
        migrations.AddField(
            model_name='preorderrequestcomment',
            name='PreorderRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='preorder.preorderrequest'),
        ),
        migrations.AlterField(
            model_name='preorderrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PreorderRequestStatus',
        ),
    ]
