# Generated by Django 5.2.1 on 2025-05-19 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0002_remove_preorderrequestcomment_preorder_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorderrequest',
            old_name='delivery_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='preorderrequest',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='preorderrequest',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='preorderrequest',
            name='zip_code',
            field=models.CharField(default=0, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Enter a valid 6-digit ZIP code')]),
            preserve_default=False,
        ),
    ]
