# Generated by Django 5.2.1 on 2025-05-19 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0003_rename_delivery_address_preorderrequest_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderrequest',
            name='custom_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='preorderrequest',
            name='recipient_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='preorderrequest',
            name='recipient_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='preorderrequest',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='preorderrequest',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='preorderrequest',
            name='recipient_zip_code',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Enter a valid 6-digit ZIP code')]),
        ),
    ]
